version: 0.2

env:
  variables:
    ENVIRONMENT: ${ENVIRONMENT}

phases:
  pre_build:
    commands:

      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Fetching Git commit hash...
      - GIT_COMMIT_HASH=$(git rev-parse HEAD)
      - echo Building Docker image...
      - echo $IMAGE_REPO_NAME:$GIT_COMMIT_HASH
      - docker build -t ${IMAGE_REPO_NAME}:${GIT_COMMIT_HASH} .
      - IMAGE_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$GIT_COMMIT_HASH"
      - IMAGE_URI=$(echo ${IMAGE_URI} | tr -d '[:space:]')
      - docker tag ${IMAGE_REPO_NAME}:${GIT_COMMIT_HASH} ${IMAGE_URI}

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push ${IMAGE_URI}